### ISSUE TITLE
Ignoring games vs. bots causes incorrent xp tracking

### ISSUE THREAD

**Issue by Zoxjib** [barrett777/Heroes.ReplayParser#15]
Games vs. bots give XP however are ignored by HotsLogs, causing discrepancies between actual character level and tracked character level.

**Comment by lorddev** [comment]
This is not an issue.  If a user plays so much A.I. that their level is inaccurate on HotsLogs then the user isn't the target user base of HotsLogs, which is geared towards PvP rankings.

**Comment by barrett777** [comment]
Well it's not an issue because the Character Level comes from the replay file, not from sum of experience

The Character Level in the replay file is your Character Level before the game was played.  Most often this discrepancy is seen when you level a Hero to 5 or 10 and don't play them again.  Because of this, they will show as 4 or 9 until you play them again
