### ISSUE TITLE
Ana Q hit rate calculator

### ISSUE THREAD

**Issue by paviad** [barrett777/Heroes.ReplayParser#82]
Hi, how would I go about calculating the hit rate of Ana's q from a replay? I'm a veteran C# programmer, a few tips should be enough

**Comment by koliva8245** [comment]
Calculating hit rates with abilities isn't possible.  The replays keep track of actions/events, so in this case the it will keep track of when Ana's abilities is used but you won't know if it hit anything.

**Comment by paviad** [comment]
I can correlate heals with Q's at least that's the intention also I can calculate the heal target based on hero locations at the Q event and the Q direction

**Comment by barrett777** [comment]
This unfortunately probably isn't possible for a few reasons.  You can find some more info here: https://github.com/Blizzard/heroprotocol/issues/27

As kolivia mentioned, the replay file keeps track of user actions.  You may be able to see if Ana tries to use her 'Q' ability (though that is a big problem by itself), and you would know what direction she tries to cast it.  That's about it though, as that is all the replay file needs in order to replay the game.

You probably won't know if she casts it successfully, for example if she was stunned when trying to cast it or something.  You probably won't know if it hits another hero, as hero locations aren't very precise in the replay file (at least how my library is tracking them).  They are good enough general location, but not enough that you can pick out which hero is hit by an ability like this.

**Comment by paviad** [comment]
So the problem is recreating the game state based on replay data? In theory can we use the existing game DLL's to do that?

**Comment by barrett777** [comment]
Maybe, though you're getting into uncharted territory.  You may find more info in the Starcraft 2 community as well.  HotS replay format and game engine are based on Starcraft 2's engine, and they've had many more years of trying to pull more data from the replay file. Good luck :)

**Comment by paviad** [comment]
What about running the entire game through a debugger and monitoring the memory?

**Comment by barrett777** [comment]
That's beyond my expertise, so I can't really help with that.  Be careful though, that sounds like it would be against Blizzard's terms of service.
