### ISSUE TITLE
Foole's MPQTool is distributed within the published package

### ISSUE THREAD

**Issue by martijnhoekstra** [barrett777/Heroes.ReplayParser#98]
Foole's MPQTool is published as source of this package. That's problematic for multiple reasons, among which:

* It's plagiarism. The author is declared as only Ben Barrett, while the software was written by Foole
* It conflicts with software written against other sources of MPQTool. If MPQTool is in some way a transitive dependency and you also have a dependency on this package, you will have clashing class names

**Comment by barrett777** [comment]
It's not plagiarism, it is published under MIT license: https://github.com/barrett777/Heroes.ReplayParser/blob/master/Heroes.ReplayParser/Foole.Mpq/BitStream.cs#L1-L28

The MIT license lets anyone include it in their library, as long as they don't claim ownership, and include that license.  As far as I know, the whole point of MIT license is to be very permissive with what you can do with it.  That's why this Heroes.ReplayParser library is also under MIT license.

I decided to include MPQTool directly because I was having trouble publishing this library to NuGet otherwise.  MPQTool hasn't been updated in years, and probably won't need any changes for the life of Hots anyway, so I think this is fine.

**Comment by martijnhoekstra** [comment]
The package I downloaded very clearly states its author is Ben Barrett. Licenses have nothing to do with plagiarism.
